### ISSUE TITLE
MVP Relayer Tracking Issue

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/quantum-gravity-bridge#44]
## Summary
The QBG is significantly simpler than the normal gravity bridge, and can therefore fit into a significantly simpler design. Notably, since the bridge is only one way, it only requires one or more relayers.

### Core
- [ ] Create an RPC endpoint for `DataCommitment` [#620](https://github.com/celestiaorg/celestia-core/issues/620)

### App
- [ ] Copy over portions of the gravity module
- [ ] Add a parameter that indicates the frequency for which the validators are expected to sign DataCommitments
- [ ] Add MsgSubmitDataCommitment and corresponding functionality

### QGB
- [ ] remove more code
- [ ] modify relayer to also query for DataCommitments
- [ ] #9 

Even though the gravity bridge supports certain types of [slashing](https://github.com/Gravity-Bridge/Gravity-Bridge/blob/main/spec/slashing-spec.md), I didn't include this in MVP as it is not strictly necessary.
